### ISSUE TITLE
How to install server 

### ISSUE THREAD

**Issue by jayeshIT** [DouglasHennrich/titanium-socket.io-chat#1]
How to install server for this,

**Comment by DouglasHennrich** [comment]
Hi @jayeshIT!
You should first copy the app.js and package.json into the server folder. Then you need to run your terminal and go to server folder and write "sudo npm install" to install all the server's dependencies.

After do that you need to run "node app.js" to start the server... you should see "listening on http://localhost:3000" on terminal.

this is it! your server are running on "http://localhost:3000"

**Comment by DouglasHennrich** [comment]
a
